#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-scripts/.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the testnet publish + smoke test of the x connector.
# Companion to docs/TESTNET_RUNBOOK.md (the checklist and the refusal matrix
# live there). Values land in scripts/.env — the operator's file, gitignored.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# The wasm a workspace member builds lands in the REPO ROOT's target/, no
# matter where the wizard is run from — so everything below uses an absolute
# path rooted at this script's location.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WASM="$ROOT/target/wasm32-wasip2/release/x-connector.wasm"
# Every later command (build, outlayer, scripts/, scripts/.env) is
# repo-root-relative; run from anywhere.
cd "$ROOT"

banner "x connector — testnet publish + smoke test"

# ── 1. prerequisites ──────────────────────────────────────────────────────
stage "Prerequisites"
MISSING=()
for tool in cargo python3 shasum; do
  command -v "$tool" >/dev/null 2>&1 || MISSING+=("$tool")
done
command -v outlayer >/dev/null 2>&1 || {
  [ -x "$HOME/.local/bin/outlayer" ] && export PATH="$HOME/.local/bin:$PATH" || MISSING+=("outlayer (curl -fsSL https://raw.githubusercontent.com/out-layer/outlayer-cli/main/install.sh | sh)")
}
command -v near >/dev/null 2>&1     || MISSING+=("near (npm i -g near-cli)")
command -v wasm-tools >/dev/null 2>&1 || MISSING+=("wasm-tools (cargo install wasm-tools)")
if (( ${#MISSING[@]} )); then
  warn "missing: ${MISSING[*]}"
  confirm "Continue anyway (only the steps whose tools exist will run)?" || { say "Install the tools above, then re-run."; exit 1; }
else
  say "all tools present."
fi
rustup target list --installed 2>/dev/null | grep -q wasm32-wasip2 || rustup target add wasm32-wasip2 || true

# ── 2. build ───────────────────────────────────────────────────────────────
stage "Build (fail-closed checks inside)"
say "Running x/build.sh — the wasm, the manifest section, the task import,"
say "the manifest/code/README agreement, the 2MB limit, the SHA256."
if confirm "Build now?"; then
  (cd "$ROOT/x" && ./build.sh) || { warn "build failed — fix it before publishing"; exit 1; }
else
  say "Keeping the existing artefact."
fi
[ -f "$WASM" ] || { warn "no wasm at $WASM — build first"; exit 1; }
HASH=$(shasum -a 256 "$WASM" | cut -d' ' -f1)
write_env WASM_SHA256 "$HASH"
say "SHA256 (= the version_key everywhere below): $HASH"

# ── 3. login testnet ───────────────────────────────────────────────────────
stage "outlayer login (testnet) — for the upload"
say "Upload needs NEAR-key auth (near_key), not a wallet key. Run this in"
say "another terminal:"
say "    outlayer login testnet"
say "It prompts for your testnet Account ID + ed25519 private key and stores"
say "them in ~/.outlayer/testnet/ (macOS Keychain)."
open_url "https://testnet.mynearwallet.com/create"
step "If you need a testnet account first: create one at the opened page, fund it at the testnet faucet, then log in."
pause "Press Enter once you have logged in (outlayer whoami says so)."
outlayer whoami testnet 2>/dev/null || warn "outlayer whoami testnet did not answer — check the login"

# ── 4. upload ──────────────────────────────────────────────────────────────
stage "Upload the wasm to FastFS"
say "Anyone may upload: the uploader shows in the URL only, the contract"
say "records url + hash, the worker verifies the hash before executing."
outlayer upload "$WASM" || { warn "upload failed"; exit 1; }
ask FASTFS_URL "Paste the FastFS URL that upload printed:"
write_env FASTFS_URL "$FASTFS_URL"
step "Verify the URL serves exactly those bytes (indexing takes 1–2 minutes):"
say "    curl -fsSL '$FASTFS_URL' | shasum -a 256   # = $HASH"
pause "Press Enter once the hash matches."

# ── 5. the version — SIGNED BY THE NAMESPACE ACCOUNT ───────────────────────
stage "add_version — signed by connectors.outlayer.testnet"
say "This is the hard part of publishing a connector: the project id must be"
say "    connectors.outlayer.testnet/x"
say "and 'outlayer deploy' signs as the identity IT has stored — which would"
say "publish <you>/x: a project the registry does not recognise as a connector,"
say "with no price and no fee. The version is added BY the namespace account."
ask NAMESPACE_HOLDER "Do you hold the connectors.outlayer.testnet key? (yes / no — 'no' means the OutLayer team signs) [yes/no]:"
if [[ "$NAMESPACE_HOLDER" == "yes" ]]; then
  step "The namespace account's key must be in near-cli's legacy keychain."
  confirm "Run add_version now (set_active: FALSE — nothing runs until the activation)?" && \
  URL="$FASTFS_URL" HASH="$HASH" scripts/publish.sh x testnet version || warn "add_version did not run"
else
  say "Hand the OutLayer team this message (their curation/program agreement is ticket #8):"
  say "    Please add_version for project 'x':"
  say "      url:  $FASTFS_URL"
  say "      hash: $HASH"
  say "      source: {\"WasmUrl\": {\"url\": \"<above>\", \"hash\": \"<above>\", \"build_target\": \"wasm32-wasip2\"}}"
  say "      set_active: false   ← so nothing runs until the activation"
  say "    (scripts/publish.sh x testnet version runs the same call once their key is in the keychain.)"
  write_env NAMESPACE_HANDOFF "pending"
fi

# ── 6. price rows — SIGNED BY THE CONTRACT OWNER ───────────────────────────
stage "Price rows — the contract owner signs"
say "Until prices exist, EVERY connector call is refused 400 unknown_operation"
say "— an unpriced project is not a free one. Prices go on chain AND the"
say "coordinator's cache is refreshed; x/set-prices.sh does both halves."
ask PRICE_HOLDER "Do you hold the contract owner key + coordinator admin token? [yes/no]:"
if [[ "$PRICE_HOLDER" == "yes" ]]; then
  confirm "Run x/set-prices.sh testnet now?" && x/set-prices.sh testnet || warn "set-prices did not run"
else
  say "Hand the OutLayer team:"
  say "    Please set_project_pricing for connectors.outlayer.testnet/x —"
  say "    status/me/confirm/task_* free; post 10000 (\$0.01); developer_share_bp 0."
  say "    (x/set-prices.sh testnet is the exact call, with the price/manifest check.)"
  write_env PRICE_HANDOFF "pending"
fi

# ── 7. the author's row — OUR OAuth client ─────────────────────────────────
stage "Secrets: the AUTHOR row (our X OAuth client)"
say "The manifest names author_secrets.profile = 'author'. An account connected"
say "through the connect page brings only a refresh token; THIS row's client"
say "completes it at run time. The publishing account stores it."
open_url "https://developer.x.com/en/portal/dashboard"
step "From your X developer app (the OAuth 2.0 Client ID + Client Secret,"
step "with 'Offline access' and 'tweet.write'/'users.read'/'tweet.read' scopes enabled):"
ask_secret X_CLIENT_ID "Paste the OAuth 2.0 Client ID:"
ask_secret X_CLIENT_SECRET "Paste the OAuth 2.0 Client Secret:"
confirm "Store them now as the project's 'author' profile?" && \
outlayer secrets set "{\"X_OAUTH_CLIENT_ID\":\"$X_CLIENT_ID\",\"X_OAUTH_CLIENT_SECRET\":\"$X_CLIENT_SECRET\"}" \
  --project connectors.outlayer.testnet/x --profile author || warn "author row not stored"

# ── 8. the owner's row — the test account's credential ──────────────────────
stage "Secrets: the OWNER row (the test X account)"
say "The row the call names in secrets_ref: profile 'x', stored by the OWNER of"
say "the test account, whitelisting the agent's wallet account BY NAME."
open_url "https://app.outlayer.ai/connect/x"
say "If the connect page is not live yet (#18), store by hand: a refresh token"
say "from the test account's OAuth consent (offline.access), pasted below."
ask_secret X_REFRESH_TOKEN "Paste the test account's refresh token:"
ask AGENT_WALLET "The agent wallet account to whitelist (e.g. agent.testnet):"
ask X_POLICY "The owner's policy JSON [default {"max_per_day":10}]:"
X_POLICY="${X_POLICY:-{"max_per_day":10}}"
confirm "Store the owner row + policy now?" && \
outlayer secrets set "$(python3 -c 'import json,sys; print(json.dumps({"X_REFRESH_TOKEN": sys.argv[1]}))' "$X_REFRESH_TOKEN")" \
  --project connectors.outlayer.testnet/x --profile x \
  --access "whitelist:$AGENT_WALLET" && \
outlayer secrets update "$(python3 -c 'import json,sys; print(json.dumps({"X_POLICY": json.dumps(json.loads(sys.argv[1]), separators=(",", ":"))}))' "$X_POLICY")" \
  --project connectors.outlayer.testnet/x --profile x || warn "owner row not stored (run the two outlayer secrets commands by hand)"

# ── 9. a payment key ────────────────────────────────────────────────────────
stage "A payment key for the calling wallet"
say "Every connector call needs X-Payment-Key, free operations included."
ask KEY_KIND "Which key? trial (first week, 50 calls) / funded [trial/funded]:"
if [[ "$KEY_KIND" == "funded" ]]; then
  outlayer keys create || warn "keys create failed"
  ask_secret PAYMENT_KEY "Paste the key it printed (owner:nonce:secret — shown ONCE):"
else
  ask WALLET_API_KEY "Paste the wallet's wk_ API key (from POST /register):"
  outlayer keys trial-key --api-key "$WALLET_API_KEY" || warn "trial-key failed"
  ask_secret PAYMENT_KEY "Paste the trial key it printed:"
fi
write_env PAYMENT_KEY "$PAYMENT_KEY"
set_secret PAYMENT_KEY "$PAYMENT_KEY"

# ── 10. smoke: status + me ──────────────────────────────────────────────────
stage "Smoke: status proves the credential, me shows the handle"
say "    PAYMENT_KEY=... outlayer run connectors.outlayer.testnet/x '{\"operation\":\"status\"}'"
PAYMENT_KEY="$PAYMENT_KEY" outlayer run connectors.outlayer.testnet/x '{"operation":"status"}' \
  || warn "status refused — read the refusal against runbook §3.1"
PAYMENT_KEY="$PAYMENT_KEY" outlayer run connectors.outlayer.testnet/x '{"operation":"me"}' \
  || warn "me refused — read the refusal against runbook §3.2"
say "Pass = status: output.success true, credential ok, granted_scope carries"
say "tweet.write, the policy, sent_today 0. me: the test account's handle."

# ── 11. smoke: the REAL post ────────────────────────────────────────────────
stage "Smoke: the real post (irreversible — it goes to x.com)"
ask POST_TEXT "The text to post [default gm — first post through the x connector]:"
POST_TEXT="${POST_TEXT:-gm — first post through the x connector}"
confirm "Post \"$POST_TEXT\" from the test account NOW?" || { say "Skipped — the runbook's other checks still stand."; skip_post=1; }
if [[ "${skip_post:-0}" != "1" ]]; then
  PAYMENT_KEY="$PAYMENT_KEY" outlayer run connectors.outlayer.testnet/x \
    "$(python3 -c 'import json,sys; print(json.dumps({"operation": "post", "text": sys.argv[1]}))' "$POST_TEXT")" || warn "post refused — runbook §3.3"
  ask TWEET_URL "Paste the tweet url from the answer:"
  write_env TWEET_URL "$TWEET_URL"
fi

# ── 12. the refusal matrix + rollback ───────────────────────────────────────
stage "Refusal matrix + rollback (runbook §4 + §6)"
say "The ordered refusal calls and what each pass looks like live in"
say "docs/TESTNET_RUNBOOK.md §4 — walk them in order and tick the results"
say "table at the bottom. The two the wizard can drive:"
confirm "Run the no-secrets_ref refusal check now?" && \
PAYMENT_KEY="$PAYMENT_KEY" outlayer run connectors.outlayer.testnet/x \
  '{"operation":"status"}' 2>&1 | grep -q "no credential" && say "  ✓ refused as expected" || say "  (read the answer against §4.2)"
say "Rollback (§6): activate the PRIOR version's hash —"
say "    HASH=<prior> scripts/publish.sh x testnet rollback"
say "— exercised ONCE, then forward again. Record both in the results table."

finish
say "Next: fill the results table in docs/TESTNET_RUNBOOK.md with the dates"
say "and outcomes of every check. Mainnet (docs/MAINNET_RUNBOOK.md) comes"
say "after the curation review (#8) and a fully green testnet runbook."
